### ISSUE TITLE
Publish package to npmjs.org

### ISSUE THREAD

**Issue by davidkarlsen** [github/dependency-submission-toolkit#14]
Can you publish the package to npmjs, because it is so much hassle using githubs internal repos, I can't afford jumping through all the hoops just to get started...

**Comment by caquino** [comment]
While setting up a development environment to work on [actions/go-dependency-submission](https://github.com/actions/go-dependency-submission) that depends on this codebase, executing `npm install` fails requiring credentials.

```
532 timing command:ci Completed in 80633ms
533 verbose stack HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="GitHub Package Registry"
533 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:88:17
533 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
534 verbose statusCode 401
535 verbose pkgid @github/dependency-submission-toolkit@https://npm.pkg.github.com/download/@github/dependency-submission-toolkit/1.1.2/742faf4570a1f30532adc02edde4b27b7bd6b9439ce9bb39c2322eaca07239e1
536 verbose cwd /workspaces/mvn-dependency-submission
537 verbose Linux 5.10.104-linuxkit
538 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "ci"
539 verbose node v16.14.2
540 verbose npm  v8.5.0
541 error code E401
542 error Incorrect or missing password.
543 error If you were trying to login, change your password, create an
543 error authentication token or enable two-factor authentication then
543 error that means you likely typed your password in incorrectly.
543 error Please try again, or recover your password at:
543 error     https://www.npmjs.com/forgot
543 error
543 error If you were doing some other operation then your saved credentials are
543 error probably out of date. To correct this please try logging in again with:
543 error     npm login
```

Is this something expected? I'm opening this issue to double-check, as it feels weird to require such credentials for an open-source project.

**Comment by lseppala** [comment]
Yes, absolutely. This is in the pipeline and we're working to get it approved so we can publish to npmjs.org and not require authentication to download the library. Apologies for the hassle while we get our paperwork done.

In the meantime, @caquino, you can authenticate by running the following your project directory:
```
npm login --scope=@github --registry=https://npm.pkg.github.com
```
Your username is your GitHub username, and your password will be a personal access token ([instructions on how to create here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)) with at least the 'read:packages' authorization.

I'll leave this issue up and close once we have the package published to npmjs.org

**Comment by lseppala** [comment]
`@github/dependency-submission-toolkit= has been published to the public npmjs.com registry: https://www.npmjs.com/package/@github/dependency-submission-toolkit

No more authentication is required to install the library. 

Sorry for the hassle, and thanks for raising the issue!
