### ISSUE TITLE
The npm registry is missing version v1.2.4

### ISSUE THREAD

**Issue by peter-murray** [github/dependency-submission-toolkit#30]
The npm registry is missing the 1.2.4 version of this, which has been tagged on the repository.

I need access to this version to complete the updates on the `@actions/core` version `1.10.0` to remove the `set-output` warnings when using this toolkit.

![Screenshot 2022-10-19 at 09 16 26](https://user-images.githubusercontent.com/681306/196636146-c30f4350-157a-4cfe-a69d-e458781ee048.png)

**Comment by jonjanego** [comment]
Latest versions are all publishing fine now.

https://www.npmjs.com/package/@github/dependency-submission-toolkit?activeTab=versions
