### ISSUE TITLE
Clearer documentation regarding branches shown

### ISSUE THREAD

**Issue by Gby56** [github/dependency-submission-toolkit#46]
Hello !
We're currently playing with the Maven submission toolkit, and I think this is nowhere to be found, but it seems like the "Insights" dependency section of a repository is only showing the default branch submissions/detections of dependencies right ?
This led me down a rabbit hole, I noticed the submission API has a notion of `ref` for the branch scanned/analyzed, but we're testing things on a non-default branch and it's not showing the dependencies anywhere.

Are there any plans to show different dependency graphs for each branch ? We play with other SCA scanners and we can switch branches, which makes sense for maintenance branches etc...

Thanks !

**Comment by febuiles** [comment]
@Gby56 Apologies for the very late reply! Dependency Graph does not support branches outside of the default one. I think the toolkit should work just fine if support was to be added, but I don't know about any plans to do that in the short term.
