### ISSUE TITLE
Opam Dependency Submission

### ISSUE THREAD

**Issue by smorimoto** [github/dependency-submission-toolkit#62]
We've done a lot of work over the last few years to integrate the dependency submission API with opam, OCaml's official package manager. See this post for details: https://discuss.ocaml.org/t/ann-set-up-ocaml-analysis

The next thing I want to do is provide decent support for opam packages on GitHub.

It would be great to be able to publish vulnerabilities on GitHub and/or such as which repositories your library is used in!

**Comment by smorimoto** [comment]
@jonjanego

**Comment by smorimoto** [comment]
Ref: https://github.com/github/advisory-database/issues/1897

**Comment by smorimoto** [comment]
Ref: https://github.com/orgs/community/discussions/19663

**Comment by jonjanego** [comment]
Thanks for filing this issue @smorimoto .  Could you elaborate more on what you mean by 'provide decent support for opam packages on GitHub'?

**Comment by smorimoto** [comment]
@jonjanego I would like to add support to the OCaml packages like the npm packages have here.
We now have a collection of packages on the official site, and we would love to link to them on GitHub Dependency graph tab, and some packages have GitHub Repository info, so we would like to link to GitHub repository instead.

**Comment by smorimoto** [comment]
Hmm... Thinking about this again, it seems hard to link repositories with just the information from the purl. Another idea is that the specification of the URL of ocaml.org can be easily composited with just the information from the purl, so it would be ideal to use it?

#### Spec

```
https://ocaml.org/p/[PACKAGE NAME]/[PACKAGE VERSION]
```

#### Example

```
https://ocaml.org/p/dune/3.13.0
```

**Comment by jonjanego** [comment]
Thanks for the suggestion @smorimoto !  At this time, adding OCaml support natively into the dependency graph functionality isn't something on our roadmap, but we'll certainly keep it in mind for the future.
